# fly.toml app configuration file generated for xxl-bot-summarizer on 2025-08-17T15:16:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xxl-bot-summarizer'
primary_region = 'waw'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# Add persistent volume for database
[mounts]
  source = "bot_data"
  destination = "/app/data"